# Generated by Django 4.0.3 on 2022-05-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GisMeteoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_parsed', models.DateTimeField(auto_now_add=True, verbose_name='Время парсинга')),
                ('date_observation', models.DateField(verbose_name='Дата')),
                ('time_observation', models.CharField(choices=[('0:00', '0:00'), ('3:00', '3:00'), ('6:00', '6:00'), ('9:00', '9:00'), ('12:00', '12:00'), ('15:00', '15:00'), ('18:00', '18:00'), ('21:00', '21:00')], max_length=5, verbose_name='Время')),
                ('value', models.PositiveSmallIntegerField(verbose_name='Значение')),
            ],
        ),
    ]
