# Generated by Django 4.0.3 on 2022-05-02 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counterparty', '0002_alter_counterparty_options'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='counterparty.counterparty', verbose_name='Поставщик'),
        ),
    ]
